# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz_guncel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 900)
        MainWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #f8cdda, stop:1 #f39c12); /* Gündoğumu Pembe ve Turuncu */\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 30, 311, 161))
        self.label.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:1 #a1c6ea);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnYukle = QtWidgets.QPushButton(self.centralwidget)
        self.btnYukle.setGeometry(QtCore.QRect(40, 100, 241, 121))
        self.btnYukle.setStyleSheet("QPushButton {\n"
"    background-color: #dcd6f7;\n"
"    color: #2c3e50;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons_gui/gallery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnYukle.setIcon(icon)
        self.btnYukle.setIconSize(QtCore.QSize(50, 50))
        self.btnYukle.setObjectName("btnYukle")
        self.btnGri = QtWidgets.QPushButton(self.centralwidget)
        self.btnGri.setGeometry(QtCore.QRect(20, 300, 251, 91))
        self.btnGri.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons_gui/greyscale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGri.setIcon(icon1)
        self.btnGri.setIconSize(QtCore.QSize(50, 50))
        self.btnGri.setObjectName("btnGri")
        self.btnBinary = QtWidgets.QPushButton(self.centralwidget)
        self.btnBinary.setGeometry(QtCore.QRect(300, 300, 261, 91))
        self.btnBinary.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons_gui/dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBinary.setIcon(icon2)
        self.btnBinary.setIconSize(QtCore.QSize(50, 50))
        self.btnBinary.setObjectName("btnBinary")
        self.btnRotate = QtWidgets.QPushButton(self.centralwidget)
        self.btnRotate.setGeometry(QtCore.QRect(590, 300, 221, 91))
        self.btnRotate.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons_gui/Adsız tasarım.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRotate.setIcon(icon3)
        self.btnRotate.setIconSize(QtCore.QSize(70, 70))
        self.btnRotate.setObjectName("btnRotate")
        self.btnCrop = QtWidgets.QPushButton(self.centralwidget)
        self.btnCrop.setGeometry(QtCore.QRect(850, 300, 211, 91))
        self.btnCrop.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 14px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons_gui/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCrop.setIcon(icon4)
        self.btnCrop.setIconSize(QtCore.QSize(50, 50))
        self.btnCrop.setObjectName("btnCrop")
        self.btnZoom = QtWidgets.QPushButton(self.centralwidget)
        self.btnZoom.setGeometry(QtCore.QRect(20, 410, 241, 81))
        self.btnZoom.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoom.setIcon(icon5)
        self.btnZoom.setIconSize(QtCore.QSize(70, 60))
        self.btnZoom.setObjectName("btnZoom")
        self.btnRenk = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenk.setGeometry(QtCore.QRect(280, 410, 301, 81))
        self.btnRenk.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 14px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons_gui/colour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRenk.setIcon(icon6)
        self.btnRenk.setIconSize(QtCore.QSize(45, 50))
        self.btnRenk.setObjectName("btnRenk")
        self.btnHistogram = QtWidgets.QPushButton(self.centralwidget)
        self.btnHistogram.setGeometry(QtCore.QRect(590, 410, 221, 81))
        self.btnHistogram.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 204117.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHistogram.setIcon(icon7)
        self.btnHistogram.setIconSize(QtCore.QSize(65, 65))
        self.btnHistogram.setObjectName("btnHistogram")
        self.btnTopla = QtWidgets.QPushButton(self.centralwidget)
        self.btnTopla.setGeometry(QtCore.QRect(10, 510, 261, 81))
        self.btnTopla.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-03 131552.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTopla.setIcon(icon8)
        self.btnTopla.setIconSize(QtCore.QSize(70, 70))
        self.btnTopla.setObjectName("btnTopla")
        self.btnCarp = QtWidgets.QPushButton(self.centralwidget)
        self.btnCarp.setGeometry(QtCore.QRect(300, 510, 261, 81))
        self.btnCarp.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons_gui/ChatGPT Image May 3, 2025, 02_15_49 PM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCarp.setIcon(icon9)
        self.btnCarp.setIconSize(QtCore.QSize(70, 70))
        self.btnCarp.setObjectName("btnCarp")
        self.btnParlaklik = QtWidgets.QPushButton(self.centralwidget)
        self.btnParlaklik.setGeometry(QtCore.QRect(10, 820, 231, 61))
        self.btnParlaklik.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 160830.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnParlaklik.setIcon(icon10)
        self.btnParlaklik.setIconSize(QtCore.QSize(60, 60))
        self.btnParlaklik.setObjectName("btnParlaklik")
        self.btnGauss = QtWidgets.QPushButton(self.centralwidget)
        self.btnGauss.setGeometry(QtCore.QRect(590, 510, 221, 81))
        self.btnGauss.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 161014.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGauss.setIcon(icon11)
        self.btnGauss.setIconSize(QtCore.QSize(60, 60))
        self.btnGauss.setObjectName("btnGauss")
        self.btnAdaptif = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdaptif.setGeometry(QtCore.QRect(850, 510, 211, 81))
        self.btnAdaptif.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-03 140236.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdaptif.setIcon(icon12)
        self.btnAdaptif.setIconSize(QtCore.QSize(65, 65))
        self.btnAdaptif.setObjectName("btnAdaptif")
        self.btnSobel = QtWidgets.QPushButton(self.centralwidget)
        self.btnSobel.setGeometry(QtCore.QRect(10, 610, 261, 81))
        self.btnSobel.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 204137.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSobel.setIcon(icon13)
        self.btnSobel.setIconSize(QtCore.QSize(65, 65))
        self.btnSobel.setObjectName("btnSobel")
        self.btnGurultu = QtWidgets.QPushButton(self.centralwidget)
        self.btnGurultu.setGeometry(QtCore.QRect(300, 610, 231, 91))
        self.btnGurultu.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-03 132003.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGurultu.setIcon(icon14)
        self.btnGurultu.setIconSize(QtCore.QSize(80, 80))
        self.btnGurultu.setObjectName("btnGurultu")
        self.btnMean = QtWidgets.QPushButton(self.centralwidget)
        self.btnMean.setGeometry(QtCore.QRect(850, 610, 211, 81))
        self.btnMean.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 204851.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMean.setIcon(icon15)
        self.btnMean.setIconSize(QtCore.QSize(65, 65))
        self.btnMean.setObjectName("btnMean")
        self.btnMedian = QtWidgets.QPushButton(self.centralwidget)
        self.btnMedian.setGeometry(QtCore.QRect(590, 610, 221, 81))
        self.btnMedian.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../icons_gui/Ekran görüntüsü 2025-05-04 204857.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMedian.setIcon(icon16)
        self.btnMedian.setIconSize(QtCore.QSize(65, 65))
        self.btnMedian.setObjectName("btnMedian")
        self.btnBlur = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlur.setGeometry(QtCore.QRect(840, 410, 231, 81))
        self.btnBlur.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../icons_gui/Adsız tasarım (5).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBlur.setIcon(icon17)
        self.btnBlur.setIconSize(QtCore.QSize(70, 70))
        self.btnBlur.setObjectName("btnBlur")
        self.btnDilate = QtWidgets.QPushButton(self.centralwidget)
        self.btnDilate.setGeometry(QtCore.QRect(20, 720, 241, 81))
        self.btnDilate.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../icons_gui/Adsız tasarım (2).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDilate.setIcon(icon18)
        self.btnDilate.setIconSize(QtCore.QSize(70, 70))
        self.btnDilate.setObjectName("btnDilate")
        self.btnErode = QtWidgets.QPushButton(self.centralwidget)
        self.btnErode.setGeometry(QtCore.QRect(850, 710, 211, 81))
        self.btnErode.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        self.btnErode.setIcon(icon18)
        self.btnErode.setIconSize(QtCore.QSize(70, 70))
        self.btnErode.setObjectName("btnErode")
        self.btnAcma = QtWidgets.QPushButton(self.centralwidget)
        self.btnAcma.setGeometry(QtCore.QRect(300, 720, 231, 81))
        self.btnAcma.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        self.btnAcma.setIcon(icon18)
        self.btnAcma.setIconSize(QtCore.QSize(70, 70))
        self.btnAcma.setObjectName("btnAcma")
        self.btnKapama = QtWidgets.QPushButton(self.centralwidget)
        self.btnKapama.setGeometry(QtCore.QRect(590, 710, 221, 81))
        self.btnKapama.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        self.btnKapama.setIcon(icon18)
        self.btnKapama.setIconSize(QtCore.QSize(70, 70))
        self.btnKapama.setObjectName("btnKapama")
        self.btnKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.btnKaydet.setGeometry(QtCore.QRect(850, 810, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnKaydet.setFont(font)
        self.btnKaydet.setStyleSheet("\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-weight: bold;")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../icons_gui/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKaydet.setIcon(icon19)
        self.btnKaydet.setIconSize(QtCore.QSize(50, 50))
        self.btnKaydet.setObjectName("btnKaydet")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 220, 501, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:1 #a1c6ea); /* Beyaz ve Pastel Mavi */\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.btnHistogramGenisletme = QtWidgets.QPushButton(self.centralwidget)
        self.btnHistogramGenisletme.setGeometry(QtCore.QRect(290, 810, 241, 81))
        self.btnHistogramGenisletme.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 16px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        self.btnHistogramGenisletme.setIcon(icon7)
        self.btnHistogramGenisletme.setIconSize(QtCore.QSize(65, 65))
        self.btnHistogramGenisletme.setObjectName("btnHistogramGenisletme")
        self.btnRenkGraytoRGB = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenkGraytoRGB.setGeometry(QtCore.QRect(550, 810, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btnRenkGraytoRGB.setFont(font)
        self.btnRenkGraytoRGB.setStyleSheet("QPushButton {\n"
"    background-color: #a8e6cf;\n"
"    color: #2e2e2e;\n"
"    font-size: 12px;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"}\n"
"")
        self.btnRenkGraytoRGB.setIcon(icon6)
        self.btnRenkGraytoRGB.setIconSize(QtCore.QSize(50, 50))
        self.btnRenkGraytoRGB.setObjectName("btnRenkGraytoRGB")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Görüntü İşleme Projesi Arayüzü"))
        self.btnYukle.setText(_translate("MainWindow", "Görsel Yükle (.bmp)"))
        self.btnGri.setText(_translate("MainWindow", "Gri Dönüşüm"))
        self.btnBinary.setText(_translate("MainWindow", "Binary Dönüşüm"))
        self.btnRotate.setText(_translate("MainWindow", "  Görüntü Döndür"))
        self.btnCrop.setText(_translate("MainWindow", "Görüntü Kırp"))
        self.btnZoom.setText(_translate("MainWindow", "Görüntü Yakınlaştırma"))
        self.btnRenk.setText(_translate("MainWindow", "Renk Uzayı Dönüşümü (RGB->GRAY)"))
        self.btnHistogram.setText(_translate("MainWindow", "Histogram Germe"))
        self.btnTopla.setText(_translate("MainWindow", "   Görüntü Toplama"))
        self.btnCarp.setText(_translate("MainWindow", "Görüntü Çarpma"))
        self.btnParlaklik.setText(_translate("MainWindow", "Parlaklık Artır"))
        self.btnGauss.setText(_translate("MainWindow", "Gauss Konvolüsyon"))
        self.btnAdaptif.setText(_translate("MainWindow", "Adaptif Eşikleme"))
        self.btnSobel.setText(_translate("MainWindow", "   Sobel Kenar Bulma"))
        self.btnGurultu.setText(_translate("MainWindow", "  Gürültü Ekle"))
        self.btnMean.setText(_translate("MainWindow", "  Mean Filtre"))
        self.btnMedian.setText(_translate("MainWindow", " Median Filtre"))
        self.btnBlur.setText(_translate("MainWindow", "      Blurring"))
        self.btnDilate.setText(_translate("MainWindow", "Genişletme"))
        self.btnErode.setText(_translate("MainWindow", "    Aşındırma"))
        self.btnAcma.setText(_translate("MainWindow", "      Açma"))
        self.btnKapama.setText(_translate("MainWindow", "       Kapama"))
        self.btnKaydet.setText(_translate("MainWindow", "    Sonucu Kaydet"))
        self.label_2.setText(_translate("MainWindow", "                           Lütfen yapmak istediğiniz işlemi seçiniz"))
        self.btnHistogramGenisletme.setText(_translate("MainWindow", "Histogram genişletme"))
        self.btnRenkGraytoRGB.setText(_translate("MainWindow", "Renk Uzayı Dönüşümü (GRAY->RGB)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
